name: Next.js CI/CD Pipeline

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Lint Code (optional)
        run: |
          if [ -f .eslintrc.js ] || [ -f .eslintrc.json ]; then
            npm run lint
          fi

      - name: Run Tests
        run: |
          if [ -f package.json ]; then
            npm test -- --watchAll=false
          fi

      - name: Build Next.js App
        run: npm run build

      - name: Export Static Site (optional for SSG)
        if: ${{ exists('next.config.js') }}
        run: |
          if grep -q "output: 'export'" next.config.js; then
            npm run export
          fi

      - name: Upload Build Artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build
          path: |
            .next/
            out/
